/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/contact`; params?: Router.UnknownInputParams; } | { pathname: `/error-boundary`; params?: Router.UnknownInputParams; } | { pathname: `/game`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/potfolio`; params?: Router.UnknownInputParams; } | { pathname: `/services`; params?: Router.UnknownInputParams; } | { pathname: `/support`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/contact-tab` | `/contact-tab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/portfolio-tab` | `/portfolio-tab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/support-tab` | `/support-tab`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/contact`; params?: Router.UnknownOutputParams; } | { pathname: `/error-boundary`; params?: Router.UnknownOutputParams; } | { pathname: `/game`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/potfolio`; params?: Router.UnknownOutputParams; } | { pathname: `/services`; params?: Router.UnknownOutputParams; } | { pathname: `/support`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/contact-tab` | `/contact-tab`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/portfolio-tab` | `/portfolio-tab`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/support-tab` | `/support-tab`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/contact${`?${string}` | `#${string}` | ''}` | `/error-boundary${`?${string}` | `#${string}` | ''}` | `/game${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/potfolio${`?${string}` | `#${string}` | ''}` | `/services${`?${string}` | `#${string}` | ''}` | `/support${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/contact-tab${`?${string}` | `#${string}` | ''}` | `/contact-tab${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/portfolio-tab${`?${string}` | `#${string}` | ''}` | `/portfolio-tab${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/support-tab${`?${string}` | `#${string}` | ''}` | `/support-tab${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/contact`; params?: Router.UnknownInputParams; } | { pathname: `/error-boundary`; params?: Router.UnknownInputParams; } | { pathname: `/game`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/potfolio`; params?: Router.UnknownInputParams; } | { pathname: `/services`; params?: Router.UnknownInputParams; } | { pathname: `/support`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/contact-tab` | `/contact-tab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/portfolio-tab` | `/portfolio-tab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/support-tab` | `/support-tab`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
